name: FedAHS-ENV
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # ===== Python & Core =====
  - python=3.10
  - pip=25.0.1

  # ===== CUDA  =====
  - cudatoolkit=11.8

  # ===== Scientific Core  =====
  - numpy=1.26.4
  - scipy=1.15.3
  - pandas=2.2.3
  - matplotlib=3.10.3
  - scikit-learn=1.6.1

  # ===== PyTorch  =====
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1

  # ===== pip packages =====
  - pip:
      - asttokens==3.0.0
      - brotlicffi==1.0.9.2
      - calmsize==0.1.3
      - category_encoders==2.8.1
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==7.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - deap==1.4.3
      - einops==0.8.1
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.58.0
      - fsspec==2024.2.0
      - gmpy2==2.2.1
      - graphviz==0.21
      - huggingface-hub==0.34.3
      - icecream==2.1.5
      - idna==3.10
      - imbalanced-learn==0.13.0
      - imblearn==0.0
      - jinja2==3.1.3
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - lightning-utilities==0.11.9
      - markupsafe==2.1.5
      - mkl_fft==1.3.11
      - mkl_random==1.2.8
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - opacus==1.5.4
      - opt_einsum==3.4.0
      - packaging==24.2
      - patsy==1.0.1
      - pillow==10.2.0
      - ply==3.11
      - progressbar2==4.5.0
      - psutil==7.0.0
      - pycparser==2.21
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - quantiphy==2.20
      - requests==2.32.4
      - rtdl==0.0.13
      - safetensors==0.5.3
      - setuptools==75.1.0
      - setuptools-scm==8.3.1
      - six==1.17.0
      - sklearn-compat==0.1.3
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tomli==2.2.1
      - tomli_w==1.2.0
      - torchmetrics==1.6.1
      - tqdm==4.67.1
      - typing_extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.5.0
      - wheel==0.44.0
      - win-inet-pton==1.1.0
      - zero==0.9.2
